# Generated by Django 5.0.3 on 2024-04-29 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('case_type', models.CharField(choices=[('OS', 'OS'), ('MC', 'MC'), ('CRL.MISC', 'CRL.MISC'), ('CCo', 'Consumer Complaint'), ('CN', 'Crime No.'), ('CC', 'CC'), ('WP', 'WP'), ('RFA', 'RFA'), ('WA', 'WA'), ('MFA', 'MFA'), ('LRF', 'LRF'), ('RA', 'RA'), ('MA', 'MA'), ('MISC', 'MISC'), ('HRA', 'HRA'), ('CRL.APPEAL', 'CRL.APPEAL'), ('CRP', 'CRP')], max_length=100)),
                ('case_number', models.CharField(max_length=12)),
                ('representing_for', models.CharField(max_length=1000)),
                ('document_link', models.URLField()),
                ('rough_work_pic', models.ImageField(upload_to='litigation/')),
            ],
        ),
        migrations.CreateModel(
            name='NonLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('project_name', models.CharField(max_length=1000)),
                ('situation', models.TextField()),
                ('property_type', models.CharField(choices=[('Site', 'Site'), ('Villa', 'Villa'), ('Gated Community', 'Gated Community'), ('Apartment', 'Apartment'), ('Row Houses', 'Row Houses')], max_length=100)),
                ('site_no', models.CharField(max_length=1000)),
                ('present_owner', models.CharField(max_length=1000)),
                ('document_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Work2NonLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=1000)),
                ('to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField()),
                ('non_litigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonlitigation')),
                ('to', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Employees'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLigitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=1000)),
                ('details', models.TextField()),
                ('to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField()),
                ('reminder_start_date', models.DateField()),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=10)),
                ('litigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.litigation')),
                ('to', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Employees'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkNonLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('completion_date', models.DateField()),
                ('reminder_start_date', models.DateField()),
                ('non_litigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonlitigation')),
            ],
        ),
    ]
