# Generated by Django 5.0.3 on 2024-04-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonlitigation',
            name='rough_work_pic',
            field=models.ImageField(default=None, upload_to='nonlitigation/'),
            preserve_default=False,
        ),
    ]
