# Generated by Django 5.0.3 on 2024-04-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nonlitigation_rough_work_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='work2nonlitigation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work2nonlitigation',
            name='finished_in_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workligitation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workligitation',
            name='finished_in_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worknonlitigation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worknonlitigation',
            name='finished_in_time',
            field=models.BooleanField(default=False),
        ),
    ]
