# Generated by Django 5.0.3 on 2024-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_work2nonlitigation_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work2nonlitigation',
            name='finished_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workligitation',
            name='finished_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='worknonlitigation',
            name='finished_time',
            field=models.DateTimeField(null=True),
        ),
    ]
