# Generated by Django 5.0.3 on 2024-05-02 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_work2nonlitigation_case_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkNonLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_stage', models.IntegerField(default=1)),
                ('work', models.CharField(max_length=1000)),
                ('details', models.TextField(null=True)),
                ('to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('finished_time', models.DateTimeField(null=True)),
                ('finished_in_time', models.BooleanField(default=False)),
                ('non_litigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonlitigation')),
                ('to', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Employees'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Work2NonLitigation',
        ),
    ]
