# Generated by Django 5.0.3 on 2024-05-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_worknonlitigation_delete_work2nonlitigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worknonlitigation',
            name='case_stage',
        ),
        migrations.AddField(
            model_name='nonlitigation',
            name='case_stage',
            field=models.IntegerField(default=1),
        ),
    ]
