# Generated by Django 5.0.3 on 2024-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_worknonlitigation_case_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonlitigation',
            name='case_stage',
            field=models.IntegerField(default=0),
        ),
    ]
