# Generated by Django 5.0.3 on 2024-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_nonlitigation_case_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknonlitigation',
            name='reminder_start_date',
            field=models.DateField(default='2024-05-05'),
            preserve_default=False,
        ),
    ]
