# Generated by Django 5.0.3 on 2024-05-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_worknonlitigation_reminder_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateField()),
                ('amount_paid', models.IntegerField()),
                ('amount_pending', models.IntegerField()),
                ('litigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.litigation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsNonLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateField()),
                ('amount_paid', models.IntegerField()),
                ('amount_pending', models.IntegerField()),
                ('non_litigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nonlitigation')),
            ],
        ),
    ]
