# Generated by Django 5.0.3 on 2024-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_paymentslitigation_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslitigation',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
