# Generated by Django 5.0.3 on 2024-05-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_paymentslitigation_date_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentslitigation',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='paymentsnonlitigation',
            name='date_paid',
        ),
        migrations.CreateModel(
            name='PaymentsLitigationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField()),
                ('amount', models.IntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paymentslitigation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsNonLitigationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField()),
                ('amount', models.IntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paymentsnonlitigation')),
            ],
        ),
    ]
