# Generated by Django 5.0.3 on 2024-06-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_noticesent_noticereceived_noticereceivedrejoinder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticereceived',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticesent',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
