# Generated by Django 5.0.3 on 2024-06-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_noticereceived_completed_noticesent_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesent',
            name='tracking_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
