# Generated by Django 5.0.3 on 2024-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_noticesent_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesent',
            name='completion_date',
            field=models.DateField(default='2024-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticesent',
            name='sent_date',
            field=models.DateField(null=True),
        ),
    ]
