# Generated by Django 5.0.3 on 2024-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_noticesent_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticereceived',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='noticereceived',
            name='acknowledgement_received_date',
        ),
        migrations.AddField(
            model_name='noticereceived',
            name='type',
            field=models.CharField(choices=[('MC', 'MC'), ('OS', 'OS'), ('NI', 'NI'), ('Consumer', 'Consumer')], default='MC', max_length=50),
            preserve_default=False,
        ),
    ]
