# Generated by Django 5.0.3 on 2024-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
